# Site settings
email: inbox.rahmad@gmail.com
baseurl: "https://rhmdhdyt.github.io"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Rahmad Blog
description: "Halo, gue Rahmad dan gue seorang Android App Developer."
url: "https://rhmdhdyt.github.io"
twitter_username: 
default_img: 

# Profile settings
name: Rahmad Hidayat
profile_img: 
profile: "Halo, gue Rahmad dan gue seorang Android App Developer."
social:
  linkedin: "https://www.linkedin.com/in/rahmad-hidayat-56648077"
  github: "https://rhmdhdyt.github.io/"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
