# Site settings
email: inbox.rahmad@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-78477098-1

# SEO settings
title: Rahmad Stories
description: "Hello, i'm Rahmad. I'm Mobile App Developer. Enjoy my stories. You can email me at : inbox.rahmad@gmail.com"
url: "https://rhmdhdyt.github.io"
twitter_username: RHMDHDYT__
default_img: "https://i.imgur.com/8ZLmX5Cl.jpg"

# Profile settings
name: Rahmad Hidayat
profile_img: "https://i.imgur.com/8ZLmX5Cl.jpg"
profile: "Hello guys, My name is Rahmad. I'm a Mobile App Developer. I hope you'll enjoy my posts. "
social:
  linkedin-square: "https://www.linkedin.com/in/rahmad-hidayat-56648077"
  github: "https://github.com/RHMDHDYT"
  twitter-square: "https://twitter.com/RHMDHDYT__"
  soundcloud: "https://soundcloud.com/raahmaad"
  steam-square: "http://steamcommunity.com/id/raahmaad/"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

# Discuss
---
layout: default
comments: true
# other options
---
